---
- name: Clean up old packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "docker"
    - "docker-common"
    - "docker-selinux"
    - "docker-engine"

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "yum-utils"
    - "device-mapper-persistent-data"
    - "lvm2"

- name: Add docker-ce repositories
  yum_repository:
    name: "{{ item.value.name }}"
    description: "{{ item.value.description }}"
    file: "{{ item.value.file }}"
    baseurl: "{{ item.value.base_url }}"
    gpgkey: "{{ item.value.gpg_key }}"
    gpgcheck: "{{ item.value.gpg_check }}"
    enabled: "{{ item.value.enabled }}"
  with_dict: "{{ docker_repos }}"

- name: Install Docker
  yum:
    name: "docker-ce"
    state: present

- name: Start and enable docker
  systemd: 
    name: docker
    state: started
    enabled: True


